# permissions for end users to edit endpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpoint-editor-role
rules:
- apiGroups:
  - raven.openyurt.io
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - raven.openyurt.io
  resources:
  - endpoints/status
  verbs:
  - get
