# permissions for end users to view endpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpoint-viewer-role
rules:
- apiGroups:
  - raven.openyurt.io
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - raven.openyurt.io
  resources:
  - endpoints/status
  verbs:
  - get
